### ISSUE TITLE
Bring binary support to cargo.io?

### ISSUE THREAD

**Issue by brassel** [kivikakk/diesel_ltree#14]
Hi there, 

thank you very much for this well working library to support postgres ltree in diesel!
Judging from your recent commits, the binary protocol seems to be supported now for ltree?
If so, are you considering to bring a new version to cargo.io for it?

Thanks a lot!
Cap Fim

**Comment by kivikakk** [comment]
Hiya Cap!

[It's done](https://crates.io/crates/diesel_ltree/0.2.5). (Thanks, @johnchildren!)

Enjoy,

Ashe

**Comment by brassel** [comment]
Hi Ashe,

thanks a lot for the extremely fast answer!
And I directly tried to include it in my system. 
The compiler gives me errors, however.
I have:

```
.execute(connection);
     |              ^^^^^^^ the trait `QueryFragment<Pg>` is not implemented for `diesel_ltree::Ltree`
```

Might it be that this line should have stayed? Maybe with an empty implementation?

https://github.com/kivikakk/diesel_ltree/commit/77a6d67e316afd31e5b23b6832e85ff9999ff9b9#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L46

Sorry to bother you with this!
Cap Fim

**Comment by johnchildren** [comment]
> Hi Ashe,
> 
> thanks a lot for the extremely fast answer! And I directly tried to include it in my system. The compiler gives me errors, however. I have:
> 
> ```
> .execute(connection);
>      |              ^^^^^^^ the trait `QueryFragment<Pg>` is not implemented for `diesel_ltree::Ltree`
> ```
> 
> Might it be that this line should have stayed? Maybe with an empty implementation?
> 
> [77a6d67#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L46](https://github.com/kivikakk/diesel_ltree/commit/77a6d67e316afd31e5b23b6832e85ff9999ff9b9#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L46)
> 
> Sorry to bother you with this! Cap Fim

I think you are probably correct that this shouldn't have been deleted, I'll try and fix and add a test to catch this in future.

**Comment by johnchildren** [comment]
Apologies, I was on holiday and then caught covid, will try and get a PR soon.

**Comment by kivikakk** [comment]
Goodness! Hoping you're feeling much better now. Thanks for the PR!
