### ISSUE TITLE
HasSqlType impls are incorrect

### ISSUE THREAD

**Issue by sgrif** [kivikakk/diesel_ltree#3]
It doesn't look like this is currently causing anything to blow up, as you aren't using any features that could cause the oids to be actually used (pretty much only bind params which require a `ToSql` impl). That said, these impls are still very wrong. Types from extensions do *not* have stable OIDs, and you need to be using http://docs.diesel.rs/diesel/pg/struct.PgMetadataLookup.html#method.lookup_type to get the OIDs dynamically at runtime.

**Comment by kivikakk** [comment]
Thanks! Fixed in 047852c3df71d67b03ccf4b3773fcb864777a1b4.
