### ISSUE TITLE
`coerce_from_type!` is redundant

### ISSUE THREAD

**Issue by sgrif** [kivikakk/diesel_ltree#4]
As best I can tell, [these lines](https://github.com/kivikakk/diesel_ltree/blob/ae45433c2d0a58d990894b377a22342e73a2c1bb/src/lib.rs#L130-L131) can just be replaced with the [`sql_function!` macro](http://docs.diesel.rs/diesel/macro.sql_function.html) like so:

```rust
sql_function!(lquery, lquery_t, (x: Text) -> Lquery);
sql_function!(ltxtquery, ltxtquery_t, (x: Text) -> Ltxtquery);
```

which would allow the macro to be removed entirely cutting roughly 50 lines of code.

**Comment by kivikakk** [comment]
Fixed in 5251f5680dc.
