### ISSUE TITLE
Most operators are redundant with those from Diesel

### ISSUE THREAD

**Issue by sgrif** [kivikakk/diesel_ltree#5]
As best I can tell, [the majority of the operators in this crate](https://github.com/kivikakk/diesel_ltree/blob/ae45433c2d0a58d990894b377a22342e73a2c1bb/src/lib.rs#L144-L149) are redundant with those [defined by Diesel](http://docs.diesel.rs/diesel/expression_methods/trait.ExpressionMethods.html). It looks like all that's missing is a few `impl SingleValue for Ltree {}` etc

**Comment by kivikakk** [comment]
Thanks so much! Getting this down to its appropriate size finally.
