### ISSUE TITLE
Ltree doesn't implement Insertable

### ISSUE THREAD

**Issue by paolobarbolini** [kivikakk/diesel_ltree#7]
I have a table with an ltree column, but when I try to make it Insertable it tells me Insertable isn't implemented for Ltree.

    the trait `diesel::Expression` is not implemented for `diesel_ltree::types::Ltree`

Looking at <a href="https://github.com/kivikakk/diesel_ltree/blob/master/src/tests.rs#L25">your tests</a> I see you used a <b>String</b> instead of <b>Ltree</b>, but you didn't declare it Insertable since that would instead give this error:

    ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `std::string::String`
    = note: required because of the requirements on the impl of `diesel::Expression` for `&'insert std::string::String`
    = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel_ltree::types::Ltree>` for `&'insert std::string::String`

So I'm not sure how I'm supposed to derive Insertable on a table with a column of Ltree, here's my code:

```rust
// ...
use diesel_ltree::Ltree;

#[derive(Identifiable, Queryable)]
#[table_name = "objects"]
pub struct Object {
    pub id: Uuid,
    pub path: Ltree,
    // other fields..
}

#[derive(Insertable)]
//       ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `diesel_ltree::types::Ltree`
#[table_name = "objects"]
pub struct NewObject {
    pub path: Ltree, // <-- it doesn't like this, Ltree isn't Insertable
    // other fields..
}
```

What am I doing wrong? Isn't this the way inserting is supposed to be?

**Comment by kivikakk** [comment]
I last worked on this in earnest about 2 years ago, so unfortunately I can't say why I did it this way off the top of my head, nor do I have the time to work it all out again.

Sorry! I figured a response is better than none.

**Comment by paolobarbolini** [comment]
Thanks for taking the time to answer.

I'm still learning Diesel and have plenty of time to figure this out. I'll contribute back the solution when I'll find it.

**Comment by kivikakk** [comment]
Thank you, I really appreciate it! Good luck.

**Comment by greglearns** [comment]
@paolobarbolini did you find a solution to this?

**Comment by greglearns** [comment]
@kivikakk I'm working on adding Insertable support. Will you be interested in that?

**Comment by kivikakk** [comment]
@greglearns Sounds great, thank you! :heart:

**Comment by greglearns** [comment]
@kivikakk PR submitted.

**Comment by greglearns** [comment]
Issue can be closed. Solved by https://github.com/kivikakk/diesel_ltree/pull/9
